[package]
id = "vsywwcmghxgv7wl3csj65oxqggqack5z"
name = "Tangent Rider"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.0"

[dependencies]
tangent_rider_core = { path = "core" }
tangent_rider_standard_spawnables = { path = "standard_spawnables" }
