[package]
id = "b2qh3cpwjwtq4fsextoplrkuxzhsejy4"
name = "Tangent Rider Standard Spawnables"
version = "0.0.1"
content = { type = "Asset", code = true }
ambient_version = "0.3.0"

[dependencies]
tangent_schema = { deployment = "14jbn64hStNAf1lMtbcLMp" }
tangent_rider_schema = { path = "../schema", deployment = "7ao6OlBzikNjUWzmncDBtr" }

[components.is_boost_pad]
name = "Is Boost Pad"
description = "Marks an entity as a boost pad."
type = "Empty"
attributes = ["Debuggable", "Networked"]

[components.last_boost_time]
name = "Last Boost Time"
description = "The last time this boost pad was used."
type = "Duration"
attributes = ["Debuggable", "Networked"]
