[package]
id = "vrhmoduo7ycojfmefrfovrhiockmhdc2"
name = "Tangent Rider Schema"
version = "0.0.1"
content = { type = "Asset", schema = true }
ambient_version = "0.3.0"

# Player-attached
[components.player_is_ready]
type = "Empty"
name = "Is Ready"
description = "Attached to a player when they are ready to start the game."
attributes = ["Networked", "Debuggable"]

[components.player_money]
type = "U32"
name = "Player Money"
description = "The amount of money that a player has."
attributes = ["Networked", "Debuggable"]

[components.player_current_spawnable]
type = "EntityId"
name = "Current Spawnable"
description = "The spawnable that the player currently has selected."
attributes = ["Networked", "Debuggable"]

[components.player_current_spawnable_ghost]
type = "EntityId"
name = "Current Spawnable Ghost"
description = "The ghost of the spawnable that the player currently has selected (actually in-world)."
attributes = ["Networked", "Debuggable"]

[components.player_construction_mode]
type = "ConstructionMode"
name = "Construction Mode"
description = "The construction mode that the player is currently in."
attributes = ["Networked", "Debuggable"]

[enums.ConstructionMode]
description = "The construction mode that the player is currently in."
[enums.ConstructionMode.members]
Place = "The player is placing a spawnable."
RotateYaw = "The player is rotating the yaw of a spawnable."
RotatePitch = "The player is rotating the pitch of a spawnable."
RotateRoll = "The player is rotating the roll of a spawnable."

# Spawnables
[components.spawnable_name]
type = "String"
name = "Spawnable name"
description = "The name of a spawnable."
attributes = ["Networked", "Debuggable"]

[components.spawnable_cost]
type = "U32"
name = "Spawnable cost"
description = "The cost of a spawnable."
attributes = ["Networked", "Debuggable"]

[components.spawnable_main_ref]
type = "EntityId"
name = "Spawnable main ref"
description = "The entity that will be cloned and spawned."
attributes = ["Networked", "Debuggable"]

[components.spawnable_ghost_ref]
type = "EntityId"
name = "Spawnable ghost ref"
description = "The entity that is used as a ghost for this spawnable."
attributes = ["Networked", "Debuggable"]

[concepts.Spawnable]
name = "Spawnable"
description = "A spawnable"
[concepts.Spawnable.components.required]
spawnable_name = {}
spawnable_cost = {}
spawnable_main_ref = {}
spawnable_ghost_ref = {}

# Resources
[components.start_position]
type = "Vec3"
name = "Start Position"
description = "The position that the player starts at."
attributes = ["MaybeResource", "Networked", "Debuggable"]

[components.active_players]
type = { container_type = "Vec", element_type = "EntityId" }
name = "Active Players"
description = "The players that are active for this game (i.e. set of rounds). Can be different to the players in the server (as they may have joined after the game started)."
attributes = ["MaybeResource", "Networked", "Debuggable"]

[components.alive_player_queue]
type = { container_type = "Vec", element_type = "EntityId" }
name = "Alive Player Queue"
description = "The queue of players that are currently alive. Players that die will be removed from the queue."
attributes = ["MaybeResource", "Networked", "Debuggable"]

[components.game_phase]
type = "GamePhase"
name = "Game Phase"
description = "The phase of the current game."
attributes = ["MaybeResource", "Networked", "Debuggable"]

[enums.GamePhase]
description = "The phase of the current game."
[enums.GamePhase.members]
Construction = "The players are constructing the level."
Play = "The players are playing the level."
